"llm.overrides.lexicon" = "ollama/qwen3:8b  "
"llm.api.openrouter.api_key" = "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"
"memory.provider" = "qdrant"

[llm]
provider = "openrouter"
model = "openrouter/deepseek/deepseek-chat-v3.1:free"

[llm.overrides]
lexicon = "openrouter/deepseek/deepseek-chat-v3.1:free"
translator = "openrouter/deepseek/deepseek-chat-v3.1:free"
curator = "openrouter/deepseek/deepseek-chat-v3.1:free"
chat = "openrouter/deepseek/deepseek-chat-v3.1:free"
drafter = "openrouter/deepseek/deepseek-chat-v3.1:free"
critic = "openrouter/deepseek/deepseek-chat-v3.1:free"
meta_reasoner = "openrouter/deepseek/deepseek-chat-v3.1:free"
summarizer = "openrouter/deepseek/deepseek-chat-v3.1:free"
planner = "openrouter/deepseek/deepseek-chat-v3.1:free"
speechify = "openrouter/deepseek/deepseek-chat-v3.1:free"
summary = "openrouter/deepseek/deepseek-chat-v3.1:free"
study = "openrouter/deepseek/deepseek-chat-v3.1:free"

[actions.context]
study_mode_context = "hebrew_and_english"

[llm.api.openrouter]
api_key = "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"

[services.brain.sefaria]
api_url = "https://www.sefaria.org/api/"
